server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: debug

spring:
  application:
    name: amf-portal-board
  profile:
    active: default
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
